name: doc_accessibility_cli
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip:
      - fastai==2.7.14
      - fitz==0.0.1.dev2
      - langdetect==1.0.9
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - pandas==2.2.0
      - pdf2image==1.17.0
      - pdfminer==20191125
      - pillow==10.2.0
      - pypdf2==3.0.1
      - pytesseract==0.3.10
      - scipy==1.12.0
      - torch==2.2.0
      - transformers==4.37.2
